### ISSUE TITLE
Add Bucket Sort

### ISSUE THREAD

**Issue by nas5w** [nas5w/javascript-patterns#5] opened 2019-10-06 22:58 UTC
Would appreciate if someone can add Bucket Sort and associated tests for it

**Comment by gautam678** [comment] 2019-10-07 01:13
I'll work on this!

**Comment by nas5w** [comment] 2019-10-07 01:15
Great, thank you!

**Comment by gautam678** [comment] 2019-10-07 02:29
duplicate of https://github.com/nas5w/javascript-patterns/issues/27

**Closed** 2019-10-07 21:24 UTC
Labels: hacktoberfest, help wanted
